# This docker-compose file brings up an example instance.
# 
# A H2 file-based database is used as example. This is not recommended for production environments.
#
# To use this docker-compose file:
#    docker compose <command> (eg. up, down)
#
# Access the Frank!Console by navigating to `http://frank.localtest.me:8080/` or `http://localhost:8080/`.
#
services:
  frank:
    image: ghcr.io/wearefrank/{{ cookiecutter.instance_name_lc }}:${VERSION:-latest}
    environment:
      TZ: ${TIME_ZONE:-Europe/Amsterdam}
      dtap.stage: ${DTAP_STAGE:-LOC}
    volumes:
      - h2-data:/opt/frank/h2:rw
      - logs:/usr/local/tomcat/logs:rw
    networks:
      frank:
        aliases:
          - frank.localtest.me
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped

volumes:
  logs:
  h2-data:

networks:
  frank: {}
